services:
  app:
    build: .
    container_name: my-fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Comando para rodar a aplicação com hot-reload, ideal para desenvolvimento.
    # O host 0.0.0.0 é necessário para que a aplicação seja acessível de fora do contêiner.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    